#!/bin/bash

set -e

if ! make terraform-fmt; then
  echo "❌ Commit blocked: terraform format found issues."
  exit 1
fi

if ! make lint; then
  echo "❌ Commit blocked: Linting failed"
  exit 1
fi

if ! make test; then
  echo "❌ Commit blocked: Failing tests."
  exit 1
fi

echo "✅ Pre-commit checks passed."
