#!/usr/bin/env python

import sys, os, re
from subprocess import check_output, CalledProcessError

# Collect the parameters
commit_msg_filepath = sys.argv[1]
if len(sys.argv) > 2:
    commit_type = sys.argv[2]
else:
    commit_type = ''
if len(sys.argv) > 3:
    commit_hash = sys.argv[3]
else:
    commit_hash = ''

print (f"prepare-commit-msg: File: {commit_msg_filepath}\nType: {commit_type}\nHash: {commit_hash}")

branch = check_output(
    ['git', 'symbolic-ref', '--short', 'HEAD'],
    text=True
).strip()
print(f"prepare-commit-msg: On branch {branch}")

with open(commit_msg_filepath, 'r+', encoding='utf-8') as f:
    content = f.read()
    f.seek(0)
    f.write(f"[{branch}] - {content}")
